### ISSUE TITLE
Can't use New dependency graph !

### ISSUE THREAD

**Issue by polosson** [leomoon-studios/blender-light-studio#3]
Not a real issue, but a kind of warning for all users...
This addon is **incompatible** with the new dependency graph (blender 2.75a, with launch option "--enable-new-depsgraph")
It makes the lights uncontrollable, they jump from one side and the other crazily.
Cheers !

**Comment by theres1** [comment]
I hope that's just a bug in new depsgraph.
Thx for help!

**Comment by leomoon** [comment]
We'll try this again when depsgraph is fully done and is bundled with Blender by default.

**Comment by brothermechanic** [comment]
Same for me
Dont created new lights
```
Dependency cycle detected:                                                                                                                                                                                                                                                     
  BLS_LIGHT_MESH.000 depends on BLS_CONTROLLER.000 through Copy Rotation.                                                                                                                                                                                                      
  BLS_CONTROLLER.000 depends on BLS_LIGHT_MESH.000 through Driver.
```
Please, fix for new depsgraph.

**Comment by brothermechanic** [comment]
THANK YOU!
WORKS!!!
GREAT WORK!!!
