### ISSUE TITLE
Dont work with new blender 2.76 

### ISSUE THREAD

**Issue by brothermechanic** [leomoon-studios/blender-light-studio#5]
Traceback (most recent call last):
  File "/usr/share/blender/2.76/scripts/addons/src/light_operators.py", line 66, in execute
    cpanel = [ob for ob in bpy.context.scene.objects if ob.name.startswith('BLS_PANEL')][0]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by theres1** [comment]
Your path "/usr/share/blender/2.76/scripts/addons/src/light_operators.py" does not seem to be correct. Delete and then reinstall addon using zip build and 'Install from file..." button in Blender preferences.

**Comment by brothermechanic** [comment]
No, this is a bug, 
I have same install for blender 2.76 and 2.75
Now i install it manually from zip and there is...

in blender-2.76
Traceback (most recent call last):
  File "/home/yeti/.config/blender/2.76/scripts/addons/blender-light-studio/light_operators.py", line 66, in execute
    cpanel = [ob for ob in bpy.context.scene.objects if ob.name.startswith('BLS_PANEL')][0]
IndexError: list index out of range

location: <unknown location>:-1

in blender-2.75
all works!

Please update your great addon for blender-2.76))))

**Comment by theres1** [comment]
It looks like platform-specific bug in latest Blender build. Appending files via Python just doesn't work in 2.76 under Linux. For now you can use this addon only in Windows ;(

**Comment by brothermechanic** [comment]
Working!
Thank you very much!
