### ISSUE TITLE
copying lights has unintuitive behaviour

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/blender-light-studio#54]
Thanks for all the fixes, works like a charm! I think copying a light could still be improved a bit.

When you copy a light this is what right now happens:
- The light you wanted to copy remains the active one
- The light you just have copied is selected, but not the active one
- In the light list your newly created one (the copy) is selected

Now if I immediately hit "g" to move my new light I actually move the old one (the source of the copy). I would expect to move my newly created one, as this is also selected in the light list.

My suggestions:
1. completely deselect the source and make the copy the active object
or 2. keep the source selected, but make the copy the active object.

I think I would prefer solution 1 as I don't see a lot of value in keeping that selection

**Comment by leomoon** [comment]
this is fixed in LightStudio 2.10.0
