### ISSUE TITLE
Feature Request: Button to select Handle of Profile

### ISSUE THREAD

**Issue by PostPollux** [leomoon-studios/blender-light-studio#56]
I think it would be nice to have a small button in the profiles panel to select the handle of the currently selected profile. Because sometimes several handles are at the same location or the handle is inside of the product you want to lighten, so it's a bit fiddly to select it.

Maybe here:
![suggestion](https://user-images.githubusercontent.com/9008901/133577567-99146491-0a5d-4394-829e-20078c8c484f.png)

**Comment by leomoon** [comment]
this is added in LightStudio 2.10.0
