### ISSUE TITLE
Not working in Blender 3.0

### ISSUE THREAD

**Issue by Aweinberg1** [leomoon-studios/blender-light-studio#59]
It installs fine, but as soon as you create a light studio a bunch or errors occur.

**Comment by leomoon** [comment]
Hello,

Yes, we are working on a fix.

**Comment by Aweinberg1** [comment]
Awesome thank you for your work, it is very appreciate by me and the Blender community!

**Comment by rohitsakharpekar5** [comment]
Hey Hi... Any Discord server for Beta testers i would like to ne part of it

As a user i would also like add this type of flexibilitiy

https://www.braverabbit.com/braverabbit/tools/place-reflection/

To add reflections like this

**Comment by rohitsakharpekar5** [comment]
> Hello,
> 
> Yes, we are working on a fix.

Any Estimated time for 3.0 support

**Comment by leomoon** [comment]
this is fixed in LightStudio 2.10.0

**Comment by Aweinberg1** [comment]
Thank you for fixing this super appreciated! Happy holidays!
