### ISSUE TITLE
Unable to scale or move light due to type of coordinates

### ISSUE THREAD

**Issue by cortopy** [leomoon-studios/blender-light-studio#64]
When I try to scale light I'm getting this error:

![Screenshot from 2022-03-08 18-01-15](https://user-images.githubusercontent.com/8725825/157298432-e0b9d773-c47b-4dc4-a56a-c1ff39d0044a.png)

And then I click on a light in the control panel to move it, the control panel disappears

It seems that the coordinates type is not right?

I'm using blender version 3.0.1

**Comment by leomoon** [comment]
Hi,

I just downloaded Blener 3.0.1 final and it is working fine.

**Comment by leomoon** [comment]
Also what OS are you using?

I can't replicate this problem on Win10, Blender 3.0.1 final build.

**Comment by cortopy** [comment]
Thanks @leomoon for answering so quickly!

I'm using the official blender version packaged for the Linux AUR repository (I use Manjaro). Based on what you said, I downloaded the one directly from the blender website and that one works! So I guess I'll use that one when using your addon.

I was very curious as to what the difference may be. Could it be the difference in the version of Python?

The one that fails has this:

```
====================================
= Blender 3.0.1 System Information =
====================================


Blender:
====================================

version: 3.0.1, branch: makepkg (modified), commit date: 2022-01-25 17:19, hash: dc2d18018171, type: Release
build date: 2022-02-17, 00:15:03
platform: 'Linux-5.10.102-1-MANJARO-x86_64-with-glibc2.35'

Python:
====================================

version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
```

The one I downloaded has this:

```
Blender:
====================================

version: 3.0.1, branch: master, commit date: 2022-01-25 17:19, hash: dc2d18018171, type: release
build date: 2022-01-26, 00:40:57
platform: 'Linux-5.10.102-1-MANJARO-x86_64-with-glibc2.35'

Python:
====================================

version: 3.9.7 (default, Oct 11 2021, 10:06:01)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

**Comment by AndersonFiorini** [comment]
I'm using Blender 3.1 on Windows 11 and the plugin is having the same problem. In previous versions of blender, the plugin is ok.  
![Captura de tela 2022-03-09 234525](https://user-images.githubusercontent.com/54543080/157578273-862aa865-5e8d-4d43-969f-09a66fceaf76.png)

**Comment by leomoon** [comment]
Hi, Yes I created a new issue for 3.1:
https://github.com/leomoon-studios/leomoon-lightstudio/issues/65

We'll have a new version soon.

**Comment by leomoon** [comment]
this is fixed in the new version and I forgot to close it.
