### ISSUE TITLE
Using “Background Setup(Optional)”to prompt errors

### ISSUE THREAD

**Issue by 26500-R** [leomoon-studios/blender-light-studio#68]
Python: Traceback (most recent call last):
  File "C:\Users\26500\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\leomoon-lightstudio-master\light_operators.py", line 294, in execute
    bpy.context.scene.world.node_tree.nodes["Background"].inputs[0].default_value = (0.008, 0.008, 0.008, 1)
KeyError: 'bpy_prop_collection[key]: key "Background" not found'

win11 blender3,2

**Comment by leomoon** [comment]
Hi,

I'm unable to replicate it. Please note LightStudio only supports final versinos of Blender and daily builds are not supported:
https://youtu.be/UGD-RfNKG_Q

Do you have Background under World Properties? By default Blender creates "Background" node for World and this error is saying that node doesn't exist:
![image](https://user-images.githubusercontent.com/3268946/175219993-22145d91-c4aa-41bf-8c6e-daf86c6c26ad.png)

**Comment by 26500-R** [comment]
> Hi,
> 
> I'm unable to replicate it. Please note LightStudio only supports final versinos of Blender and daily builds are not supported: https://youtu.be/UGD-RfNKG_Q
> 
> Do you have Background under World Properties? By default Blender creates "Background" node for World and this error is saying that node doesn't exist: ![image](https://user-images.githubusercontent.com/3268946/175219993-22145d91-c4aa-41bf-8c6e-daf86c6c26ad.png)

Thank you，I find，Change Blender's language to English, and it can work
