### ISSUE TITLE
Support For Blender 3.2.0

### ISSUE THREAD

**Issue by beyond3dartist** [leomoon-studios/blender-light-studio#69]
Add on Not Working For Blender 3.2.0

also If i change Lights from Viewport can be possible it will update on Panel too???

**Comment by leomoon** [comment]
Hi,

I can't replicate your problem. The only issue is that the LightStudio Control Panel doesn't resize in Blender 3.2.*
![image](https://user-images.githubusercontent.com/3268946/183222212-34230c87-d0ed-45d9-86db-dddf370933a0.png)

**Comment by leomoon** [comment]
Please enable LightStudio logging by changing false to true in this line:
https://github.com/leomoon-studios/leomoon-lightstudio/blob/master/operators/__init__.py#L15

`__init__.py` on your computer (Windows) would be:
```
%appdata%\Blender Foundation\Blender\3.3\scripts\addons\leomoon-lightstudio\operators\__init__.py
```

And once Blender crashes, please include both LightStudio logs and Blender crash logs.
https://docs.blender.org/manual/en/latest/troubleshooting/crash.html

Thanks for helping us to make this plugin better.
