### ISSUE TITLE
Feature Request /Idea

### ISSUE THREAD

**Issue by Zaldor** [leomoon-studios/blender-light-studio#7]
It would be nice to have the option to "Bake" the studio setup and render out the enviroment map which would be automatically swapped, all previous setup could be hidden to be able to recover it or simply deleted, this would allow the creation of favourite setups and an easy way to share them, in my opinion.
Regards
-G

**Comment by leomoon** [comment]
I was actually thinking about that. I don't know how to make it yet.. But still you can do that. It just requires more steps:

Select all the lights in the 3D view and move them into the separate layer.
Select the main camera and in the camera settings, choose Panoramic and change the type from Fisheye Equisolid to Equirectangular.
Hit render and save it as HDR or EXR.
