### ISSUE TITLE
Sometimes Blender 3.3 quits 

### ISSUE THREAD

**Issue by hansvaneven** [leomoon-studios/blender-light-studio#70]
I have an issue where Blender 3.3 quits (disappears from screen) using Lightstudio. Hard to know what happens, one of the things I observed is that soloing and un-soloing is one of the things that make this happen from time to time, but also letting Blender run for a long time. Not sure if this is a Blender bug? I installed newest drivers for ma 3080Ti card to see it maybe it's related to my GPU drivers.

**Comment by leomoon** [comment]
Please enable LightStudio logging by changing false to true in this line:
https://github.com/leomoon-studios/leomoon-lightstudio/blob/master/operators/__init__.py#L15

`__init__.py` on your computer (Windows) would be:
```
%appdata%\Blender Foundation\Blender\3.3\scripts\addons\leomoon-lightstudio\operators\__init__.py
```

And once Blender crashes, please include both LightStudio logs and Blender crash logs.
https://docs.blender.org/manual/en/latest/troubleshooting/crash.html

Thanks for helping us to make this plugin better.
