### ISSUE TITLE
Exporting studio

### ISSUE THREAD

**Issue by brothermechanic** [leomoon-studios/blender-light-studio#8]
Hello
This is great addon! 
Thank you for developing it!
I found, that exporting studio between scenes will be great feature.
What you think?
ps: i created a package for gentoo os! https://github.com/brothermechanic/cg/tree/master/media-plugins/blender-light-studio

**Comment by leomoon** [comment]
Cool. I like it. I'll add it to ideas list.

**Comment by leomoon** [comment]
Added to future ideas.
